<link rel="stylesheet" href="/js/owl-carousel/owl.carousel.css">
<link rel="stylesheet" href="/js/owl-carousel/owl.theme.css">
<div class="row">
    <div class="large-12 columns">
	    <div id="slider" class="owl-carousel">
	        <div><img src="/img/slider1.jpg" /></div>
	        <div><img src="/img/slider2.jpg" /></div>
            <div><img src="/img/slider3.jpg" /></div>
	    </div>
    </div>
</div>

<script>
    $(document).ready(function() {
    $('.honeycombs').honeycombs({
        combWidth:260,  // width of the hexagon
        margin: -30,      // spacing between hexagon
        threshold: 3    // hide placeholder hexagons when number of hexagons in a row is more than the threshold number
    });
});
</script>

<script src="/js/owl-carousel/owl.carousel.js"></script>

<script>
$(document).ready( function(){
	$("#slider").owlCarousel({
		autoPlay : 5000,
		navigation : true,
		singleItem: true,
		autoHeight : true
	});
 });
</script>