<link rel="stylesheet" href="/js/owl-carousel/owl.carousel.css">
<link rel="stylesheet" href="/js/owl-carousel/owl.theme.css">
<div class="row">
    <div class="large-12 columns">
	    <div id="slider" class="owl-carousel">
        <?php foreach($obras as $obra) : ?>
	        <div>
            <img src="http://expresibo.com<?php echo $obra['path'];?>" />
            <fieldset>
            <legend>Cédula:</legend>
                Nombre: <?php echo $obra['nombre'] . ' '. $obra['apellido_paterno'] . ' '. $obra['apellido_materno'];?><br>
                Técnica: <?php echo $obra['tecnica'];?><br>
            </fieldset>
            </div>
        <?php endforeach; ?>
	    </div>
    </div>
</div>

<script src="/js/owl-carousel/owl.carousel.js"></script>

<script>
$(document).ready( function(){
	$("#slider").owlCarousel({
		autoPlay : 5000,
		navigation : true,
		singleItem: true,
		autoHeight : true
	});
 });
</script>