<div class="row">


<section class="Registro">
<h2>Registro</h2>
<?php if ($this->error): ?>
<p class="error">
 Hubo errores en la información ingresada, favor de verificarlos.
</p>
<?php endif ?>



<?php
        //Vista de Forma
        $form = $this->form;

        $form->setAttribute('action', $this->url(NULL, array('controller'=>'obras', 'action' => 'add')));
        $form->setAttribute('data-abide', '');
        $form->prepare();

        echo $this->form()->openTag($form);
?>
<div class="row">
        <div class="large-6 medium-4 small-12 columns">
                <div class="field">
                    <?php echo $this->formLabel($form->get('nombre')); ?>
                    <?php echo $this->formElement($form->get('nombre')); ?>
                    <small class="error">Este campo es requerido.</small>
                </div>
        </div>
        <div class="large-6 medium-4 small-12 columns">
                <div class="field">
                    <?php echo $this->formLabel($form->get('apellido_paterno')); ?>
                    <?php echo $this->formElement($form->get('apellido_paterno')); ?>
                    <small class="error">Este campo es requerido.</small>
                </div>
        </div>
        <div class="large-6 medium-4 small-12 columns">
                <div class="field">
                    <?php echo $this->formLabel($form->get('apellido_materno')); ?>
                    <?php echo $this->formElement($form->get('apellido_materno')); ?>
                    <small class="error">Este campo es requerido.</small>
                </div>
        </div>
        <div class="large-6 medium-4 small-12 columns">
                <div class="field">
                    <?php echo $this->formLabel($form->get('titulo')); ?>
                    <?php echo $this->formElement($form->get('titulo')); ?>
                    <small class="error">Este campo es requerido.</small>
                </div>
        </div>
        <div class="large-6 medium-4 small-12 columns">
                <div class="field">
                    <?php echo $this->formLabel($form->get('tecnica')); ?>
                    <?php echo $this->formElement($form->get('tecnica')); ?>
                    <small class="error">Este campo es requerido.</small>
                </div>
        </div>
        <div class="large-6 medium-4 small-12 columns">
                <div class="field">
                    <?php echo $this->formLabel($form->get('descripcion')); ?>
                    <?php echo $this->formElement($form->get('descripcion')); ?>
                    <small class="error">Este campo es requerido.</small>
                </div>
        </div>
        <div class="large-6 medium-4 small-12 columns">
                <div class="field">
                    <?php echo $this->formLabel($form->get('medidax')); ?>
                    <?php echo $this->formElement($form->get('medidax')); ?>
                    <small class="error">Este campo es requerido.</small>
                </div>
        </div>
        <div class="large-6 medium-4 small-12 columns">
                <div class="field">
                    <?php echo $this->formLabel($form->get('mediday')); ?>
                    <?php echo $this->formElement($form->get('mediday')); ?>
                    <small class="error">Este campo es requerido.</small>
                </div>
        </div>
        <div class="large-6 medium-4 small-12 columns">
                <div class="field">
                    <?php echo $this->formLabel($form->get('subgaleria')); ?>
                    <?php echo $this->formElement($form->get('subgaleria')); ?>
                    <small class="error">Este campo es requerido.</small>
                </div>
        </div>
        <div class="large-6 medium-4 small-12 columns">
                <div class="field">
                    <?php echo $this->formElement($form->get('fileupload')); ?>
                    <small class="error">Este campo es requerido.</small>
                </div>
        </div>
        <div class="large-6 medium-4 small-12 columns">
                <div class="field">
                    <?php echo $this->formLabel($form->get('activo')); ?>
                    <?php echo $this->formElement($form->get('activo')); ?>
                    <small class="error">Este campo es requerido.</small>
                </div>
        </div>
</div>
<?php echo $this->formElement($form->get('submit')); ?>

<?php echo $this->form()->closeTag() ?>


</div>
