<html>
<head>
	<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Expresibo</title>
    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="/css/foundation.css" />
    
    <script src="/js/vendor/modernizr.js"></script>
    <script src="/js/vendor/jquery.js"></script>
</head>
<body>

<div class="large-3 columns header">
    <div class="">
        <div class="large-12 columns logo">
        	<a href="/"><img src="/img/logoprepaudem.PNG" /></a>
        </div>
        <div class="large-12 columns menudiv">
        	<ul class="menu">
                <li><a href="#">Galerias</a></li>
                <li><a href="#">Convocatorias</a></li>
                <li><a href="#">Quienes somos</a></li>
                <li><a href="/registro/register/index">Registro</a></li>
            </ul>
        </div>
        <div class="large-12 columns footerdiv">
            <p>Información adicional</p>
        </div>
    </div>
</div>

<div class="large-9 columns">
    <div class="row">
        <div class="large-12 columns">
        	<?php echo $this->content; ?>
        </div>
    </div>
</div>
	
    <script src="/js/foundation.min.js"></script>
    <script src="/js/foundation/foundation.abide.js"></script>
    <script>
    $(document).foundation({
        abide : {
          patterns: {
            alphanumesp: /^[a-zA-Z0-9áéíóúÁÉÍÓÚÑñüÜ (),.#@!-:$&%*]+$/
          }
        }
      });
    </script>
	
</body>
</html>
        