<html>
<head>
	<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Expresibo</title>
    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="/css/foundation.css" />

    <script src="/js/vendor/modernizr.js"></script>
    <script src="/js/vendor/jquery.js"></script>
</head>
<body>

<div class="large-3 columns header">
    <div class="">
        <div class="large-12 columns logo">
        	<a href="/"><img src="/img/logoprepaudem.PNG" /></a>
        </div>
        <div class="large-12 columns menudiv">
        	<ul class="menu">
                <li><a href="#">Galerias</a></li>
                <li><a href="#">Convocatorias</a></li>
                <li><a href="#">Quienes somos</a></li>
                <li><a href="/registro/register/index">Registro</a></li>
            </ul>
        </div>
        <div class="large-12 columns footerdiv">
            <p>Información adicional</p>
             <div class="row">
<?php if($this->zfcUserIdentity()) :?>
    <div style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
    <h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?>!</h3>
    <a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>&nbsp;&nbsp;&nbsp;<a href="<?php echo $this->url('panelcontrol'); ?>">Menú</a>
    <div style="clear:both;"></div>
<?php endif; ?>
</div>
        </div>
    </div>
</div>

<div class="large-9 columns">
    <div class="row">
        <div class="large-12 columns">
        	<?php echo $this->content; ?>
        </div>
    </div>
</div>

    <script src="/js/foundation.min.js"></script>
    <script src="/js/foundation/foundation.abide.js"></script>
    <script>
    $(document).foundation({
        abide : {
          patterns: {
            alphanumesp: /^[a-zA-Z0-9áéíóúÁÉÍÓÚÑñüÜ (),.#@!-:$&%*]+$/
          }
        }
      });
    </script>

</body>
</html>
